site_name: Java Fundamentals


# Site tree
nav:
  - Home: index.md
  - Beginer:
    - Java - Big picture:
      - Plataform:  beginer/java-big-picture/plataform/readme.md
      - Compiling and Running:  beginer/java-big-picture/compile-run/readme.md

  
  
repo_url: https://github.com/pedrohaccorsi/java-fundamentals
repo_name: java-fundamentals
# Configuration

extra_css:
  - stylesheets/custom-colors.css

theme:
  name: material
  custom_dir: custom-assets
  favicon: java.svg
  icon:
    logo: java
    repo: fontawesome/brands/github

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    - instant
    - navigation.instant
    - navigation.tabs
    - search.highlight
  plugins:
    - search    
  palette: 
    scheme: preference
    # primary: yellow
    # accent: indigo

  font:
    text: Roboto
    code: Roboto Mono
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pedrohaccorsi/c-for-operating-systems      

markdown_extensions:
    - md_in_html
    - toc:
        permalink: true
    - admonition
    - codehilite
    - def_list
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.tabbed
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.superfences
    - pymdownx.mark 
    - pymdownx.smartsymbols
    - pymdownx.tasklist:
        custom_checkbox: true
    - toc:
        permalink: "#"
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
        options:
          custom_icons:
            - assets/.icons